# Generated by Django 4.2.16 on 2024-10-22 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0003_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='confirm_password',
        ),
    ]
